transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/proc_sys_reset_v5_0_17
vlib riviera/smartconnect_v1_0
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_register_slice_v2_1_36
vlib riviera/axi_vip_v1_1_22
vlib riviera/axi_apb_bridge_v3_0_21
vlib riviera/versal_cips_ps_vip_v1_0_14
vlib riviera/xil_defaultlib
vlib riviera/cpm4_v1_0_20
vlib riviera/cpm5_v1_0_20
vlib riviera/noc_nmu_sim_v1_0_0
vlib riviera/noc_hbm_nmu_sim_v1_0_0
vlib riviera/xlconstant_v1_1_10

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap proc_sys_reset_v5_0_17 riviera/proc_sys_reset_v5_0_17
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_register_slice_v2_1_36 riviera/axi_register_slice_v2_1_36
vmap axi_vip_v1_1_22 riviera/axi_vip_v1_1_22
vmap axi_apb_bridge_v3_0_21 riviera/axi_apb_bridge_v3_0_21
vmap versal_cips_ps_vip_v1_0_14 riviera/versal_cips_ps_vip_v1_0_14
vmap xil_defaultlib riviera/xil_defaultlib
vmap cpm4_v1_0_20 riviera/cpm4_v1_0_20
vmap cpm5_v1_0_20 riviera/cpm5_v1_0_20
vmap noc_nmu_sim_v1_0_0 riviera/noc_nmu_sim_v1_0_0
vmap noc_hbm_nmu_sim_v1_0_0 riviera/noc_hbm_nmu_sim_v1_0_0
vmap xlconstant_v1_1_10 riviera/xlconstant_v1_1_10

vlog -work xilinx_vip  -incr "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"C:/AMDDesignTools/2025.2/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/AMDDesignTools/2025.2/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work proc_sys_reset_v5_0_17 -93  -incr \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vcom -work smartconnect_v1_0 -93  -incr \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/cb42/hdl/sc_ultralite_v1_0_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_36  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/bc4b/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_22  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/b16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vcom -work axi_apb_bridge_v3_0_21 -93  -incr \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/6670/hdl/axi_apb_bridge_v3_0_vh_rfs.vhd" \

vcom -work versal_cips_ps_vip_v1_0_14 -93  -incr \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl/versal_cips_ps_vip_v1_0_rfs.vhd" \

vlog -work versal_cips_ps_vip_v1_0_14  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl/versal_cips_ps_vip_v1_0_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/sim/versal_cips_ps_vip_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/hdl/pspmc_v1_4_7_sim.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/sim/bd_70da_pspmc_0_0.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_1/hdl/xram_v1_0_1_sim.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_1/sim/bd_70da_xram_0.v" \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/bd_0/sim/bd_70da.v" \

vlog -work cpm4_v1_0_20  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/cpm4_v1_0_vl_rfs.sv" \

vlog -work cpm5_v1_0_20  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/cpm5_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_versal_cips_0_0/sim/design_1_versal_cips_0_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/sim/bd_4b24.v" \

vlog -work noc_nmu_sim_v1_0_0  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/noc_nmu_sim_v1_0_vl_rfs.sv" \

vlog -work noc_hbm_nmu_sim_v1_0_0  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/noc_hbm_nmu_sim_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm/bd_4b24_S00_AXI_nmu_0_top.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm/NOC_NMU512_SPP.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_0/hdl/bfm/bd_4b24_S00_AXI_nmu_0.sv" \

vlog -work xlconstant_v1_1_10  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../../ledblink.gen/sources_1/bd/design_1/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_1/sim/bd_4b24_const_0_0.v" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_2/hdl/bfm/bd_4b24_S01_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_2/hdl/bfm/bd_4b24_S01_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_3/hdl/bfm/bd_4b24_S02_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_3/hdl/bfm/bd_4b24_S02_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_4/hdl/bfm/bd_4b24_S03_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_4/hdl/bfm/bd_4b24_S03_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_5/hdl/bfm/bd_4b24_S04_AXI_rpu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_5/hdl/bfm/bd_4b24_S04_AXI_rpu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_6/hdl/bfm/bd_4b24_S05_AXI_nmu_0_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_6/hdl/bfm/bd_4b24_S05_AXI_nmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/rtl/bd_4b24_MC0_ddrc_0_phy_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/bd_4b24_MC0_ddrc_0_phy_ddr_responder.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/noc_mc_ddr4_v1_0_phy_xiphy_behav.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/noc_mc_ddr4_v1_0_dc.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/noc_mc_ddr4_v1_0_ddrmc_wdb.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/ddr4mc_top.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model/ddr_model.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model/ddr_model_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na/noc_na_v1_0_vl_rfs.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/bfm/bd_4b24_MC0_ddrc_0_phy.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/hdl/rtl/bd_4b24_MC0_ddrc_0_wrapper.sv" \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/hdl/rtl/bd_4b24_MC0_ddrc_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/f9c1/hdl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/078a/ttcl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/21e1/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/060f/hdl/verilog" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/2796/hdl/bfm" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/db35/hdl/bfm_hbm" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/rsb/busdef" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4/tb/ddr4_model" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/ddr4" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/hdl/noc_na" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ipshared/4f65/hdl/rtl" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0/h_files" "+incdir+../../../../ledblink.gen/sources_1/bd/design_1/ip/design_1_axi_noc_0_1/bd_0/ip/ip_7/ip_0" "+incdir+C:/AMDDesignTools/2025.2/Vivado/data/xilinx_vip/include" -l xilinx_vip -l xpm -l proc_sys_reset_v5_0_17 -l smartconnect_v1_0 -l axi_infrastructure_v1_1_0 -l axi_register_slice_v2_1_36 -l axi_vip_v1_1_22 -l axi_apb_bridge_v3_0_21 -l versal_cips_ps_vip_v1_0_14 -l xil_defaultlib -l cpm4_v1_0_20 -l cpm5_v1_0_20 -l noc_nmu_sim_v1_0_0 -l noc_hbm_nmu_sim_v1_0_0 -l xlconstant_v1_1_10 \
"../../../bd/design_1/ip/design_1_axi_noc_0_1/sim/design_1_axi_noc_0_1.v" \
"../../../bd/design_1/ip/design_1_rst_versal_cips_0_100M_0/design_1_rst_versal_cips_0_100M_0_sim_netlist.v" \
"j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_MyLEDIP_0_4/design_1_MyLEDIP_0_4_sim_netlist.v" \
"../../../bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0_sim_netlist.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/sim/design_1.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

