# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vd100.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_versal_cips_0_0/design_1_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_versal_cips_0_0 || ORIG_REF_NAME==design_1_versal_cips_0_0} -quiet] -quiet

# Block Designs: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da || ORIG_REF_NAME==bd_70da} -quiet] -quiet

# IP: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] -quiet

# IP: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_1/bd_70da_xram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_70da_xram_0 || ORIG_REF_NAME==bd_70da_xram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_noc_0_1/design_1_axi_noc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_noc_0_1 || ORIG_REF_NAME==design_1_axi_noc_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_versal_cips_0_100M_0/design_1_rst_versal_cips_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_versal_cips_0_100M_0 || ORIG_REF_NAME==design_1_rst_versal_cips_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MyLEDIP_0_4/design_1_MyLEDIP_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MyLEDIP_0_4 || ORIG_REF_NAME==design_1_MyLEDIP_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_0/design_1_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_0 || ORIG_REF_NAME==design_1_axi_smc_0} -quiet] -quiet

# XDC: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/bd_70da_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_pspmc_0_0 || ORIG_REF_NAME==bd_70da_pspmc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/ip/ip_1/bd_70da_xram_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_70da_xram_0 || ORIG_REF_NAME==bd_70da_xram_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/ip/design_1_versal_cips_0_0/bd_0/bd_70da_ooc.xdc

# XDC: j:/work/projects/versal/ledblink/hardware/ledblink.gen/sources_1/bd/design_1/design_1_ooc.xdc
